### ISSUE TITLE
Update student editor on view click

### ISSUE THREAD

**Issue by Paul2708** [Paul2708/cercet#10]
If the teacher clicks on "View", the current editor of the student is shown.
However, if the student is not typing anything, the editor shows the default template.

To avoid this, it requires an "initial request" that will be broadcasted to the student.
The student replies with his current editor content.

**Comment by Paul2708** [comment]
Backend endpoint is implemented.

**Comment by NyCodeGHG** [comment]
Frontend Implementation should work.
