### ISSUE TITLE
Server cannot find default config

### ISSUE THREAD

**Issue by Paul2708** [Paul2708/cercet#11]
I added a config file that got mounted:

```yaml
- "./config.yaml:/app/config.yaml"
```

If the config exists, everything works fine.

If the config doesn't exist, the following error occurs when using Docker:
```
backend_1   | java.io.FileNotFoundException: ./config.yaml (Is a directory)
backend_1   |   at java.base/java.io.FileInputStream.open0(Native Method)
backend_1   |   at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
backend_1   |   at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
backend_1   |   at de.paul2708.server.config.Configuration.load(Configuration.java:30)
backend_1   |   at de.paul2708.server.JavalinServer.configureAndStart(JavalinServer.java:59)
backend_1   |   at de.paul2708.server.Main.main(Main.java:7)
```
See [`Configuration.load`](https://github.com/Paul2708/cercet/blob/537e5d8176c102f7f8ecaf46210d4ba054f215f7/backend/server/src/main/java/de/paul2708/server/config/Configuration.java#L21).
If I run the jar locally, everything works fine.

**Comment by NyCodeGHG** [comment]
Should be fixed now
