### ISSUE TITLE
Timeout after 5 minutes

### ISSUE THREAD

**Issue by Paul2708** [Paul2708/cercet#12]
After 5 minutes, a timeout occurs if the socket didn't read or write.
There are two possibilities to avoid this:
1. The client sends a __heartbeat message__ every minute that follows the [message format](https://github.com/Paul2708/cercet/blob/main/documentation/endpoints.md#web-socket-endpoints).
2. __Increase the timeout__ from 5 minutes to 90 minutes since a tutorial lasts 90 minutes.

I would prefer (1) if it's possible.

**Comment by NyCodeGHG** [comment]
I would also prefer 1.

**Comment by Leon-DE** [comment]
I share NyCodeGHG's opinion.  🍡

**Comment by Paul2708** [comment]
I solved it in https://github.com/Paul2708/cercet/commit/07b656174fdefdff60c63e9ac4c4f4f64a1feb7d by sending a heartbeat message from the server to every connected client.
