### ISSUE TITLE
GitHub action

### ISSUE THREAD

**Issue by Paul2708** [Paul2708/cercet#7]
A GitHub action (CI/CD pipeline) would be fancy.

**Comment by NyCodeGHG** [comment]
It seems like I don't have permissions to setup GitHub Actions and I did not know that this closes the issue, I thought it would just be mentioned

**Comment by Paul2708** [comment]
I disable action by default if they are not needed.
I re-enabled it. Does it work?

**Comment by NyCodeGHG** [comment]
yes

**Comment by Paul2708** [comment]
Great, thanks!
